[package]
name = "hexxer"
authors = ["René Möhring <rene_moehring@gmx.de>"]
version = "0.1.1"
edition = "2021"
description = "A xxd like hexdump cli tool"
license = "MIT"
keywords = ["xxd", "hex dump"]
repository = "https://github.com/tyrdal/hexxer"

[dependencies]
clap = { version = "4.5.*", features = ["derive"] }
colored = "2.0.*"

[[bin]]
name = "hexx"
path = "src/main.rs"
